
set(target "corkytux")
set(working_dir "/tmp/CorkyTux-Launcher")
set(src_and_dest_list
    "/tmp/CorkyTux-Launcher/qml/Main.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/Main.qml"
    "/tmp/CorkyTux-Launcher/qml/Sidebar.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/Sidebar.qml"
    "/tmp/CorkyTux-Launcher/qml/GameCard.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/GameCard.qml"
    "/tmp/CorkyTux-Launcher/qml/DetailsPanel.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/DetailsPanel.qml"
    "/tmp/CorkyTux-Launcher/qml/AddGameModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/AddGameModal.qml"
    "/tmp/CorkyTux-Launcher/qml/SettingsModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/SettingsModal.qml"
    "/tmp/CorkyTux-Launcher/qml/GameSettingsModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/GameSettingsModal.qml"
    "/tmp/CorkyTux-Launcher/qml/RemoveModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/RemoveModal.qml"
    "/tmp/CorkyTux-Launcher/qml/LogModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/LogModal.qml"
    "/tmp/CorkyTux-Launcher/qml/ProtonModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/ProtonModal.qml"
    "/tmp/CorkyTux-Launcher/qml/PrefixWarningModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/PrefixWarningModal.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CButton.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CButton.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CCard.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CCard.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CComboBox.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CComboBox.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CIcon.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CIcon.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CModal.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CModal.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CSwitch.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CSwitch.qml"
    "/tmp/CorkyTux-Launcher/qml/components/CTextField.qml"
    "/tmp/CorkyTux-Launcher/build-release/CorkyTux/qml/components/CTextField.qml"

)
set(timestamp_file "/tmp/CorkyTux-Launcher/build-release/.qt/corkytux_qml.txt")
